### ISSUE TITLE
SIPMeta fails to dump data from .hic files (for multiple reasons)

### ISSUE THREAD

**Issue by ArielPaulson** [PouletAxel/SIP_metaploter#2]
Hi,

Two issues using SIPMeta 1.3.1, Java 1.8.0_102, CentOS7, command line like:

java -jar $SIPMeta hic simple $bedpe $hicfile $outdir $chrsizes $juicer_tools $bullseye 21 1000 -norm <anything> -res 10000

Issue 1: if juicer tools 1.13 as recommended on the wiki (specifically juicer_tools_1.13.02.jar), then "-norm <anything>" has no effect.  It always dies with error "Norm not available at BP_X VC" where X is the -res argument, no matter what resolution.  Basically it always tries to pull VC, and always fails, even though I can manually dump VC data at every resolution, from 1k to 1M.

Issue 2: I tried a different version of juicer tools (feature_tools_2.13.07.jar) and apparently this does dump data correctly, but then dies with a completely different issue: 

java.nio.file.NoSuchFileException: /n/core/Bioinformatics/analysis/Rohner/tb2500/cbio.tb2500.100/data/juicer_new/analysis/loops/SIP/comp/sipmeta/cave_only/Pachon/25kb/AMEX_1.1_unplaced_55/AMEX_1.1_unplaced_55_0_53027_expected.txt
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at java.nio.file.Files.newBufferedReader(Files.java:2784)
	at utils.DumpData.getExpected(DumpData.java:142)
	at multiProcessing.RunnableDumpData.run(RunnableDumpData.java:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Unknown chromosome: AMEX_1.1_unplaced_55
java.nio.file.NoSuchFileException: /n/core/Bioinformatics/analysis/Rohner/tb2500/cbio.tb2500.100/data/juicer_new/analysis/loops/SIP/comp/sipmeta/cave_only/Pachon/25kb/AMEX_1.1_unplaced_56/AMEX_1.1_unplaced_56_0_52918_expected.txt

The message itself seems confused as to whether the offending scaffold was AMEX_1.1_unplaced_55 or AMEX_1.1_unplaced_56, which are lines 80 and 81 in the $chrsizes file, respectively.  I assume this is because these chromosomes have no signal in the hic file, which is possible.  However, such a minor issue should never cause the script to die.  Besides, the input bedpe file does not even have any loops on these scaffolds.

Thanks,
Ariel

**Comment by PouletAxel** [comment]
Hi,
I will check that as soon as possible
Best
Axel
